name: "BeSmart Companion"
slug: "besmart_companion"
description: "Local setup companion for BeSmart Home Server"
version: "1.0.4"

arch:
  - aarch64

init: false
startup: services
boot: auto
host_network: true

options: {}
schema: {}
